@echo off
setlocal EnableExtensions EnableDelayedExpansion

REM ================================================================
REM build_stc51_examples.bat
REM Auto-generated by gen_build_bat.py. DO NOT EDIT MANUALLY.
REM Build all C51CC_STC51 examples with c51cc,
REM and all STC51 originals with Keil C51 for comparison.
REM ================================================================

call :resolve_path "%~dp0.." REPO_ROOT

set "C51CC_EXAMPLES=%REPO_ROOT%\code\C51CC_STC51"
set "STC51_ROOT=%REPO_ROOT%\code\STC51"
set "OUTPUT_ROOT=%REPO_ROOT%\output\stc51"
set "KEIL_BIN=%REPO_ROOT%\_tools\keil\C51\BIN"
set "KEIL_LIB=%REPO_ROOT%\_tools\keil\C51\LIB"
set "KEIL_INC=%REPO_ROOT%\_tools\keil\C51\INC"
set "INCLUDE_DIR=%C51CC_EXAMPLES%\include"
set "TMP_ROOT=%REPO_ROOT%\.tmp\stc51"

REM Allow passing custom c51cc path as first argument
if "%~1"=="" (
    set "C51CC=%REPO_ROOT%\scripts\c51cc.exe"
) else (
    call :resolve_path "%~1" C51CC
)

if not exist "%C51CC%" (
    echo [WARN] c51cc not found: %C51CC%
    set "HAS_C51CC=0"
) else (
    set "HAS_C51CC=1"
)

if not exist "%KEIL_BIN%\C51.exe" (
    echo [WARN] Keil C51 not found, skip keil builds
    set "HAS_KEIL=0"
) else (
    set "HAS_KEIL=1"
)

set "KEIL_OUT=%OUTPUT_ROOT%\keil"
set "C51CC_OUT=%OUTPUT_ROOT%\c51cc"

if exist "%OUTPUT_ROOT%" rmdir /s /q "%OUTPUT_ROOT%"
mkdir "%KEIL_OUT%" >nul 2>nul
mkdir "%C51CC_OUT%" >nul 2>nul
if exist "%TMP_ROOT%" rmdir /s /q "%TMP_ROOT%"
mkdir "%TMP_ROOT%" >nul 2>nul
REM Pre-populate TMP_ROOT\include so that ../include/... includes resolve for all examples
mkdir "%TMP_ROOT%\include" >nul 2>nul
copy /y "%INCLUDE_DIR%\reg52.h" "%TMP_ROOT%\include\reg52.h" >nul
copy /y "%INCLUDE_DIR%\delay.h" "%TMP_ROOT%\include\delay.h" >nul

set /a KEIL_OK=0
set /a KEIL_FAIL=0
set /a C51CC_OK=0
set /a C51CC_FAIL=0

echo [INFO] c51cc      : %C51CC%
echo [INFO] C51CC_EX   : %C51CC_EXAMPLES%
echo [INFO] STC51_ROOT : %STC51_ROOT%
echo [INFO] Output     : %OUTPUT_ROOT%
echo.

set "C51CC_NAME_1=2-1_led_on"
REM STC51_NAME_1 (Chinese dir name - not used)
set "C51CC_NAME_2=2-2_led_blink"
REM STC51_NAME_2 (Chinese dir name - not used)
set "C51CC_NAME_3=2-3_led_flow"
REM STC51_NAME_3 (Chinese dir name - not used)
set "C51CC_NAME_4=2-4_led_flow_plus"
REM STC51_NAME_4 (Chinese dir name - not used)
set "C51CC_NAME_5=3-1_key_led"
REM STC51_NAME_5 (Chinese dir name - not used)
set "C51CC_NAME_6=3-2_key_led_toggle"
REM STC51_NAME_6 (Chinese dir name - not used)
set "C51CC_NAME_7=3-3_key_led_binary"
REM STC51_NAME_7 (Chinese dir name - not used)
set "C51CC_NAME_8=3-4_key_led_shift"
REM STC51_NAME_8 (Chinese dir name - not used)
set "C51CC_NAME_9=4-1_nixie_static"
REM STC51_NAME_9 (Chinese dir name - not used)
set "C51CC_NAME_10=4-2_nixie_dynamic"
REM STC51_NAME_10 (Chinese dir name - not used)
set "C51CC_NAME_11=6-1_matrix_key"
REM STC51_NAME_11 (Chinese dir name - not used)
set "C51CC_NAME_12=5-1_nixie_module"
REM STC51_NAME_12 (Chinese dir name - not used)
set "C51CC_NAME_13=6-2_matrix_key_lock"
REM STC51_NAME_13 (Chinese dir name - not used)
set "C51CC_NAME_14=7-1_timer_led_mode"
REM STC51_NAME_14 (Chinese dir name - not used)
set "C51CC_NAME_15=7-2_timer_clock"
REM STC51_NAME_15 (Chinese dir name - not used)
set "C51CC_NAME_16=8-1_uart_send"
REM STC51_NAME_16 (Chinese dir name - not used)
set "C51CC_NAME_17=8-2_uart_recv"
REM STC51_NAME_17 (Chinese dir name - not used)
set "C51CC_NAME_18=9-1_matrix_led_static"
REM STC51_NAME_18 (Chinese dir name - not used)
set "C51CC_NAME_19=9-2_matrix_led_anim"
REM STC51_NAME_19 (Chinese dir name - not used)
set "C51CC_NAME_20=5-2_lcd1602_debug"
set "C51CC_NAME_21=10-1_ds1302_clock"
set "C51CC_NAME_22=10-2_ds1302_adjustable"
set "C51CC_NAME_23=11-1_buzzer_beep"
set "C51CC_NAME_24=11-2_buzzer_music"
set "C51CC_NAME_25=12-1_at24c02_storage"
set "C51CC_NAME_26=12-2_stopwatch"
set "C51CC_NAME_27=13-1_ds18b20_temp"
set "C51CC_NAME_28=13-2_ds18b20_alarm"
set "C51CC_NAME_29=14-1_lcd1602"
set "C51CC_NAME_30=15-1_led_breathing"
set "C51CC_NAME_31=15-2_dc_motor"
set "C51CC_NAME_32=16-1_adc"
set "C51CC_NAME_33=16-2_dac"
set "C51CC_NAME_34=17-1_ir_remote"
set "C51CC_NAME_35=17-2_ir_motor"

call :build_example "%C51CC_NAME_1%" "%STC51_NAME_1%"
call :build_example "%C51CC_NAME_2%" "%STC51_NAME_2%"
call :build_example "%C51CC_NAME_3%" "%STC51_NAME_3%"
call :build_example "%C51CC_NAME_4%" "%STC51_NAME_4%"
call :build_example "%C51CC_NAME_5%" "%STC51_NAME_5%"
call :build_example "%C51CC_NAME_6%" "%STC51_NAME_6%"
call :build_example "%C51CC_NAME_7%" "%STC51_NAME_7%"
call :build_example "%C51CC_NAME_8%" "%STC51_NAME_8%"
call :build_example "%C51CC_NAME_9%" "%STC51_NAME_9%"
call :build_example "%C51CC_NAME_10%" "%STC51_NAME_10%"
call :build_example "%C51CC_NAME_11%" "%STC51_NAME_11%"
call :build_example "%C51CC_NAME_12%" "%STC51_NAME_12%"
call :build_example "%C51CC_NAME_13%" "%STC51_NAME_13%"
call :build_example "%C51CC_NAME_14%" "%STC51_NAME_14%"
call :build_example "%C51CC_NAME_15%" "%STC51_NAME_15%"
call :build_example "%C51CC_NAME_16%" "%STC51_NAME_16%"
call :build_example "%C51CC_NAME_17%" "%STC51_NAME_17%"
call :build_example "%C51CC_NAME_18%" "%STC51_NAME_18%"
call :build_example "%C51CC_NAME_19%" "%STC51_NAME_19%"
call :build_example "%C51CC_NAME_20%" ""
call :build_example "%C51CC_NAME_21%" ""
call :build_example "%C51CC_NAME_22%" ""
call :build_example "%C51CC_NAME_23%" ""
call :build_example "%C51CC_NAME_24%" ""
call :build_example "%C51CC_NAME_25%" ""
call :build_example "%C51CC_NAME_26%" ""
call :build_example "%C51CC_NAME_27%" ""
call :build_example "%C51CC_NAME_28%" ""
call :build_example "%C51CC_NAME_29%" ""
call :build_example "%C51CC_NAME_30%" ""
call :build_example "%C51CC_NAME_31%" ""
call :build_example "%C51CC_NAME_32%" ""
call :build_example "%C51CC_NAME_33%" ""
call :build_example "%C51CC_NAME_34%" ""
call :build_example "%C51CC_NAME_35%" ""

echo.
echo ===== BUILD SUMMARY =====
echo c51cc : %C51CC_OK% ok, %C51CC_FAIL% fail
echo Keil  : %KEIL_OK% ok, %KEIL_FAIL% fail
echo.
goto :eof

:build_example
set "_C51CC_NAME=%~1"
set "_STC51_NAME=%~2"

echo ----- %_C51CC_NAME% -----

REM --- c51cc build ---
if "%HAS_C51CC%"=="1" (
    set "_SRC=%C51CC_EXAMPLES%\%_C51CC_NAME%\main.c"
    set "_OUT=%C51CC_OUT%\%_C51CC_NAME%"
    if not exist "!_OUT!" mkdir "!_OUT!" >nul 2>nul
    if exist "!_SRC!" (
        pushd "!_OUT!"
        "%C51CC%" -asm -hex -o main -I"%INCLUDE_DIR%" "!_SRC!" >build.log 2>&1
        if !errorlevel! equ 0 (
            echo [OK ] c51cc: %_C51CC_NAME%
            set /a C51CC_OK+=1
        ) else (
            echo [FAIL] c51cc: %_C51CC_NAME%
            type build.log
            set /a C51CC_FAIL+=1
        )
        popd
    ) else (
        echo [SKIP] c51cc: no src !_SRC!
        set /a C51CC_FAIL+=1
    )
)

REM --- Keil build ---
if "%HAS_KEIL%"=="0" goto :eof
REM All examples compiled from C51CC_STC51 (STC51 originals have Chinese dir names, inaccessible)
set "_KEIL_SRC_DIR=%C51CC_EXAMPLES%\%_C51CC_NAME%"
set "_KEIL_EXTRA_OBJ="
set "_KEIL_OUT=%KEIL_OUT%\%_C51CC_NAME%"
set "_KEIL_TMP=%TMP_ROOT%\%_C51CC_NAME%"
if not exist "%_KEIL_OUT%" mkdir "%_KEIL_OUT%" >nul 2>nul
if not exist "%_KEIL_TMP%" mkdir "%_KEIL_TMP%" >nul 2>nul
if not exist "%_KEIL_SRC_DIR%\main.c" (
    echo [SKIP] Keil: no src at %_KEIL_SRC_DIR%\main.c
    set /a KEIL_FAIL+=1
    goto :eof
)
copy /y "%_KEIL_SRC_DIR%\main.c" "%_KEIL_TMP%\main.c" >nul
REM Check if main.c calls Delay() - if so, also compile delay.c
findstr /i "Delay(" "%_KEIL_TMP%\main.c" >nul 2>&1
if not errorlevel 1 (
    copy /y "%INCLUDE_DIR%\delay.c" "%_KEIL_TMP%\delay.c" >nul
    set "_KEIL_EXTRA_OBJ=delay.obj"
)
REM For 6-1: delay.c is already handled above (it also calls Delay)
pushd "%_KEIL_TMP%"
call :do_keil_compile
set "_KEIL_RC=%errorlevel%"
if !_KEIL_RC! equ 0 (
    copy /y main.hex "!_KEIL_OUT!\main.hex" >nul 2>nul
    copy /y main.lst "!_KEIL_OUT!\main.lst" >nul 2>nul
    echo [OK ] Keil: %_C51CC_NAME%
    set /a KEIL_OK+=1
) else (
    echo [FAIL] Keil: %_C51CC_NAME%
    set /a KEIL_FAIL+=1
)
popd

goto :eof

:do_keil_compile
REM Compile
"%KEIL_BIN%\C51.exe" main.c LARGE CODE OPTIMIZE(8,SPEED) INCDIR(%KEIL_INC%,%KEIL_INC%\Atmel) OBJECT(main.obj) PRINT(main.lst) >c51.log 2>&1
if %errorlevel% gtr 1 (
    echo [FAIL] Keil compile:
    type c51.log
    exit /b 1
)
REM Compile extra source files if any
if not "%_KEIL_EXTRA_OBJ%"=="" (
    call :do_keil_compile_extra
    if errorlevel 1 exit /b 1
)
REM Assemble startup
"%KEIL_BIN%\A51.EXE" "%KEIL_LIB%\STARTUP.A51" OBJECT(STARTUP.obj) >a51.log 2>&1
if %errorlevel% neq 0 (
    echo [FAIL] A51:
    type a51.log
    exit /b 1
)
REM Link (include extra objs if any)
if "%_KEIL_EXTRA_OBJ%"=="" (
    set "_BL51_OBJS=main.obj,STARTUP.obj"
) else (
    set "_BL51_OBJS=main.obj,%_KEIL_EXTRA_OBJ%,STARTUP.obj"
)
"%KEIL_BIN%\BL51.EXE" %_BL51_OBJS% TO main CODE(0x0000) >bl51.log 2>&1
if %errorlevel% gtr 1 (
    echo [FAIL] BL51 link:
    type bl51.log
    exit /b 1
)
REM Generate HEX
"%KEIL_BIN%\OH51.EXE" MAIN >oh51.log 2>&1
if not exist MAIN.hex (
    echo [FAIL] OH51 no hex:
    type oh51.log
    exit /b 1
)
REM OH51 names the file MAIN.hex (uppercase)
if not exist main.hex rename MAIN.hex main.hex >nul 2>nul
exit /b 0

:do_keil_compile_extra
for %%f in (%_KEIL_EXTRA_OBJ%) do (
    set "_EXTRA_SRC=%%~nf.c"
    set "_EXTRA_OBJ=%%f"
    call :do_keil_compile_one_extra
    if !errorlevel! neq 0 exit /b 1
)
exit /b 0

:do_keil_compile_one_extra
"%KEIL_BIN%\C51.exe" %_EXTRA_SRC% LARGE CODE OPTIMIZE(8,SPEED) INCDIR(%KEIL_INC%,%KEIL_INC%\Atmel) OBJECT(%_EXTRA_OBJ%) >c51_extra.log 2>&1
if %errorlevel% gtr 1 (
    echo [FAIL] Keil compile extra:
    type c51_extra.log
    exit /b 1
)
exit /b 0

:resolve_path
set "%~2=%~f1"
goto :eof
