#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
gen_build_bat.py: generate build_stc51_examples.bat with proper GBK encoding
Run this from repo root: python scripts/gen_build_bat.py
"""

import os
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(SCRIPT_DIR)
OUTPUT_BAT = os.path.join(SCRIPT_DIR, "build_stc51_examples.bat")

# Mapping: (c51cc_name, stc51_original_name)
EXAMPLES = [
    ("2-1_led_on", "2-1 点亮一个LED"),
    ("2-2_led_blink", "2-2 LED闪烁"),
    ("2-3_led_flow", "2-3 LED流水灯"),
    ("2-4_led_flow_plus", "2-4 LED流水灯Plus"),
    ("3-1_key_led", "3-1 独立按键控制LED亮灭"),
    ("3-2_key_led_toggle", "3-2 独立按键控制LED状态"),
    ("3-3_key_led_binary", "3-3 独立按键控制LED显示二进制"),
    ("3-4_key_led_shift", "3-4 独立按键控制LED移位"),
    ("4-1_nixie_static", "4-1 静态数码管显示"),
    ("4-2_nixie_dynamic", "4-2 动态数码管显示"),
    ("6-1_matrix_key", "6-1 矩阵键盘"),
]


def make_bat():
    lines = []
    a = lines.append

    a("@echo off")
    a("setlocal EnableExtensions EnableDelayedExpansion")
    a("")
    a("REM ================================================================")
    a("REM build_stc51_examples.bat")
    a("REM Auto-generated by gen_build_bat.py. DO NOT EDIT MANUALLY.")
    a("REM Build all C51CC_STC51 examples with c51cc,")
    a("REM and all STC51 originals with Keil C51 for comparison.")
    a("REM ================================================================")
    a("")
    a('call :resolve_path "%~dp0.." REPO_ROOT')
    a("")
    a('set "C51CC_EXAMPLES=%REPO_ROOT%\\code\\C51CC_STC51"')
    a('set "STC51_ROOT=%REPO_ROOT%\\code\\STC51"')
    a('set "OUTPUT_ROOT=%REPO_ROOT%\\output\\stc51"')
    a('set "KEIL_BIN=%REPO_ROOT%\\_tools\\keil\\C51\\BIN"')
    a('set "KEIL_LIB=%REPO_ROOT%\\_tools\\keil\\C51\\LIB"')
    a('set "KEIL_INC=%REPO_ROOT%\\_tools\\keil\\C51\\INC"')
    a('set "INCLUDE_DIR=%C51CC_EXAMPLES%\\include"')
    a('set "TMP_ROOT=%REPO_ROOT%\\.tmp\\stc51"')
    a("")
    a("REM Allow passing custom c51cc path as first argument")
    a('if "%~1"=="" (')
    a('    set "C51CC=%REPO_ROOT%\\scripts\\c51cc.exe"')
    a(") else (")
    a('    call :resolve_path "%~1" C51CC')
    a(")")
    a("")
    a('if not exist "%C51CC%" (')
    a("    echo [WARN] c51cc not found: %C51CC%")
    a('    set "HAS_C51CC=0"')
    a(") else (")
    a('    set "HAS_C51CC=1"')
    a(")")
    a("")
    a('if not exist "%KEIL_BIN%\\C51.exe" (')
    a("    echo [WARN] Keil C51 not found, skip keil builds")
    a('    set "HAS_KEIL=0"')
    a(") else (")
    a('    set "HAS_KEIL=1"')
    a(")")
    a("")
    a('set "KEIL_OUT=%OUTPUT_ROOT%\\keil"')
    a('set "C51CC_OUT=%OUTPUT_ROOT%\\c51cc"')
    a("")
    a('if exist "%OUTPUT_ROOT%" rmdir /s /q "%OUTPUT_ROOT%"')
    a('mkdir "%KEIL_OUT%" >nul 2>nul')
    a('mkdir "%C51CC_OUT%" >nul 2>nul')
    a('if exist "%TMP_ROOT%" rmdir /s /q "%TMP_ROOT%"')
    a('mkdir "%TMP_ROOT%" >nul 2>nul')
    a("")
    a("set /a KEIL_OK=0")
    a("set /a KEIL_FAIL=0")
    a("set /a C51CC_OK=0")
    a("set /a C51CC_FAIL=0")
    a("")
    a("echo [INFO] c51cc      : %C51CC%")
    a("echo [INFO] C51CC_EX   : %C51CC_EXAMPLES%")
    a("echo [INFO] STC51_ROOT : %STC51_ROOT%")
    a("echo [INFO] Output     : %OUTPUT_ROOT%")
    a("echo.")
    a("")

    # Generate per-example calls
    for idx, (c51cc_name, stc51_name) in enumerate(EXAMPLES, 1):
        var_suffix = str(idx)
        a(f'set "C51CC_NAME_{var_suffix}={c51cc_name}"')
        a(f'set "STC51_NAME_{var_suffix}={stc51_name}"')

    a("")
    for idx in range(1, len(EXAMPLES) + 1):
        a(f'call :build_example "%C51CC_NAME_{idx}%" "%STC51_NAME_{idx}%"')

    a("")
    a("echo.")
    a("echo ===== BUILD SUMMARY =====")
    a("echo c51cc : %C51CC_OK% ok, %C51CC_FAIL% fail")
    a("echo Keil  : %KEIL_OK% ok, %KEIL_FAIL% fail")
    a("echo.")
    a("goto :eof")
    a("")

    # :build_example subroutine
    a(":build_example")
    a('set "_C51CC_NAME=%~1"')
    a('set "_STC51_NAME=%~2"')
    a("")
    a("echo ----- %_C51CC_NAME% -----")
    a("")
    a("REM --- c51cc build ---")
    a('if "%HAS_C51CC%"=="1" (')
    a('    set "_SRC=%C51CC_EXAMPLES%\\%_C51CC_NAME%\\main.c"')
    a('    set "_OUT=%C51CC_OUT%\\%_C51CC_NAME%"')
    a('    if not exist "!_OUT!" mkdir "!_OUT!" >nul 2>nul')
    a('    if exist "!_SRC!" (')
    a('        pushd "!_OUT!"')
    a('        "%C51CC%" -asm -hex -o main -I"%INCLUDE_DIR%" "!_SRC!" >build.log 2>&1')
    a("        if !errorlevel! equ 0 (")
    a("            echo [OK ] c51cc: %_C51CC_NAME%")
    a("            set /a C51CC_OK+=1")
    a("        ) else (")
    a("            echo [FAIL] c51cc: %_C51CC_NAME%")
    a("            type build.log")
    a("            set /a C51CC_FAIL+=1")
    a("        )")
    a("        popd")
    a("    ) else (")
    a("        echo [SKIP] c51cc: no src !_SRC!")
    a("        set /a C51CC_FAIL+=1")
    a("    )")
    a(")")
    a("")
    a("REM --- Keil build ---")
    a('if "%HAS_KEIL%"=="0" goto :eof')
    a('set "_KEIL_SRC_DIR=%STC51_ROOT%\\%_STC51_NAME%"')
    a('set "_KEIL_OUT=%KEIL_OUT%\\%_C51CC_NAME%"')
    a('set "_KEIL_TMP=%TMP_ROOT%\\%_C51CC_NAME%"')
    a('if not exist "%_KEIL_OUT%" mkdir "%_KEIL_OUT%" >nul 2>nul')
    a('if not exist "%_KEIL_TMP%" mkdir "%_KEIL_TMP%" >nul 2>nul')
    a('if not exist "%_KEIL_SRC_DIR%\\main.c" (')
    a("    echo [SKIP] Keil: no src at %_KEIL_SRC_DIR%\\main.c")
    a("    set /a KEIL_FAIL+=1")
    a("    goto :eof")
    a(")")
    a('copy /y "%_KEIL_SRC_DIR%\\main.c" "%_KEIL_TMP%\\main.c" >nul')
    a('pushd "%_KEIL_TMP%"')
    a("call :do_keil_compile")
    a('set "_KEIL_RC=%errorlevel%"')
    a("if !_KEIL_RC! equ 0 (")
    a('    copy /y main.hex "!_KEIL_OUT!\\main.hex" >nul 2>nul')
    a('    copy /y main.lst "!_KEIL_OUT!\\main.lst" >nul 2>nul')
    a("    echo [OK ] Keil: %_C51CC_NAME%")
    a("    set /a KEIL_OK+=1")
    a(") else (")
    a("    echo [FAIL] Keil: %_C51CC_NAME%")
    a("    set /a KEIL_FAIL+=1")
    a(")")
    a("popd")
    a("")
    a("goto :eof")
    a("")

    # :do_keil_compile - runs in cwd=tmp dir, no outer parentheses context
    a(":do_keil_compile")
    a("REM Compile")
    a(
        '"%KEIL_BIN%\\C51.exe" main.c LARGE CODE OPTIMIZE(8,SPEED) INCDIR(%KEIL_INC%,%KEIL_INC%\\Atmel) OBJECT(main.obj) PRINT(main.lst) >c51.log 2>&1'
    )
    a("if %errorlevel% gtr 1 (")
    a("    echo [FAIL] Keil compile:")
    a("    type c51.log")
    a("    exit /b 1")
    a(")")
    a("REM Assemble startup")
    a(
        '"%KEIL_BIN%\\A51.EXE" "%KEIL_LIB%\\STARTUP.A51" OBJECT(STARTUP.obj) >a51.log 2>&1'
    )
    a("if %errorlevel% neq 0 (")
    a("    echo [FAIL] A51:")
    a("    type a51.log")
    a("    exit /b 1")
    a(")")
    a("REM Link")
    a('"%KEIL_BIN%\\BL51.EXE" main.obj,STARTUP.obj TO main CODE(0x0000) >bl51.log 2>&1')
    a("if %errorlevel% neq 0 (")
    a("    echo [FAIL] BL51 link:")
    a("    type bl51.log")
    a("    exit /b 1")
    a(")")
    a("REM Generate HEX")
    a('"%KEIL_BIN%\\OH51.EXE" MAIN >oh51.log 2>&1')
    a("if not exist MAIN.hex (")
    a("    echo [FAIL] OH51 no hex:")
    a("    type oh51.log")
    a("    exit /b 1")
    a(")")
    a("REM OH51 names the file MAIN.hex (uppercase)")
    a("if not exist main.hex rename MAIN.hex main.hex >nul 2>nul")
    a("exit /b 0")
    a("")
    a(":resolve_path")
    a('set "%~2=%~f1"')
    a("goto :eof")
    a("")

    return "\n".join(lines)


if __name__ == "__main__":
    content = make_bat()
    # Write as GBK (Chinese Windows CMD requires GBK/ANSI)
    with open(OUTPUT_BAT, "w", encoding="gbk", errors="replace") as f:
        f.write(content)
    print(f"Generated: {OUTPUT_BAT}")
    print(f"Size: {os.path.getsize(OUTPUT_BAT)} bytes")
